# makefile tool
#
#================================================================
#   Copyright (C) 2022 Sangfor Ltd. All rights reserved.
#   
#    Filename: makefile
#      Author: Andy
#     Created: 2022-02-11 09:27:07
# Description: 
#
#================================================================

all:
	py2applet --make-setup main.py icon.png
	python3 setup.py py2app

clean:
	@rm -rf build dist setup.py
